buildscript {
    repositories {
        mavenCentral()
        maven { url = "https://files.minecraftforge.net/maven" }
        maven { url = "https://maven.minecraftforge.net/" }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'

version = '1.0'
group = 'com.ezlauncher'
archivesBaseName = 'EZLauncher'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.19.2'

    runs {
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                ezlauncher {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenCentral()
    maven { url = "https://files.minecraftforge.net/maven" }
    maven { url = "https://maven.minecraftforge.net/" }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.19.2-43.2.0'
}

processResources {
    inputs.property "version", project.version

    filesMatching('META-INF/mods.toml') {
        expand 'version': project.version
    }
}

jar {
    manifest {
        attributes([
            "Specification-Title"     : "ezlauncher",
            "Specification-Vendor"    : "ezlauncher",
            "Specification-Version"   : "1",
            "Implementation-Title"    : project.name,
            "Implementation-Version"  : project.version,
            "Implementation-Vendor"   : "ezlauncher"
        ])
    }
}
