pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://maven.minecraftforge.net/" }
    }
}

buildscript {
    repositories {
        mavenCentral()
        maven { url = "https://maven.minecraftforge.net/" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.11'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = '1.0'
group = 'com.ezlauncher'
archivesBaseName = 'EZLauncher'

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.19.2-43.2.0"
    runDir = "run"
    mappings = "officialMojangMappings"
}

repositories {
    mavenCentral()
    maven { url = "https://maven.minecraftforge.net/" }
}

dependencies {
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
    }

    expand 'version':project.version, 'mcversion':project.minecraft.version
}
